### ISSUE TITLE
Error on twig template 'RedCodeTreeBundle:CRUD:tree.html.twig'

### ISSUE THREAD

**Issue by Kleinast** [redco/sonata-admin-tree-bundle#4]
Hello,

I use the dev-master bundle with sonata admin 3.16

I override this sonata admin config:

sonata_admin:
    templates:
        outer_list_rows_tree: 'RedCodeTreeBundle:CRUD:tree.html.twig'

For use the bundle template for tree instead of not existing sonata one. But I get this error:
Variable "_sonata_admin" does not exist.

Is it a bug or did I do something wrong ?

Thanks

**Comment by maZahaca** [comment]
Hi, 
did you follow instructions from the readme file?

**Comment by Kleinast** [comment]
Hi, I am pretty sûre to respect the readme + change the outer tree templace of sonata with the redco one on sonata admin config. It was working for a while, but doesn't work anymore since i did composer update.

**Comment by maZahaca** [comment]
Could you provide the full error trace as symfony provides it?
Could you provider your current composer.lock file, so we can reproduce this issue?

**Comment by Kleinast** [comment]
Hi, 
Sorry for the delay, I made others tests and In fact it work, I made a mistake, and it seem that with your bundle if you load the sonata view ?_list_mode=tree on entity where treecrud feature is not plug. 

Finaly I think the only things miss is there is no "?_list_mode=" bouton for change view display when you had clicked on tree view display.
So now it's more an evolution/improvement than a real bug.

**Comment by Kleinast** [comment]
Hi,
It's me again, after small try, It seem if I just add "&nbsp;" in template:
RedCode\TreeBundle\Resources\views\CRUD\tree.html.twig
line 115:
{% block list_filters_actions %}
    &nbsp;
{% endblock %}
The nav bar appear with bouton for display view

#5

**Comment by maZahaca** [comment]
Ok, thanks
