### ISSUE TITLE
Can't install package from Composer

### ISSUE THREAD

**Issue by AsyncLegs** [redco/sonata-admin-tree-bundle#6]
After fresh symfony3 project creating, i've ran:
composer require redcode/tree-bundle

```
  [InvalidArgumentException]
  Could not find package redcode/tree-bundle at any version for your minimum-stability (stable).
  Check the package spelling or your minimum-stability
```

**Comment by maZahaca** [comment]
As I remember it supports up to Symfony 2.8.
Configuration my be different or incorrect for version 3.0

**Comment by DimaSerikov** [comment]
Try composer require redcode/tree-bundle @dev

**Comment by AsyncLegs** [comment]
@DimaSerikov Sorry for delay, i did it later, and it works, but anyway thanks for answer!
